TRUNCATE TABLE dbo.HATA
TRUNCATE TABLE dbo.MONTAJ
TRUNCATE TABLE dbo.MONTAJ_PERSONEL
TRUNCATE TABLE dbo.MONTAJKOTA
TRUNCATE TABLE dbo.PERSONELBILGI
TRUNCATE TABLE dbo.SIPARIS
TRUNCATE TABLE dbo.SIPARISNOSAYAC