USE [master]
GO
CREATE LOGIN [KobsisAppUser] WITH PASSWORD=N'1Qaz2wSx!', DEFAULT_DATABASE=[KOBSISAppDB], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [KOBSISAppDB]
GO
CREATE USER [KobsisAppUser] FOR LOGIN [KobsisAppUser]
GO
USE [KOBSISAppDB]
GO
EXEC sp_addrolemember N'db_owner', N'AckAppUser'
GO